//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyEmployeeMast
    {
        public long CompanyEmployeeID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual CompanyMast CompanyMast { get; set; }
        public virtual EmployeeMaster EmployeeMaster { get; set; }
    }
}
