//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServices.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int TranDetailId { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> MRP { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TransctionMaster TransctionMaster { get; set; }
    }
}
