//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryAttributeDetail
    {
        public long CatAttributeDetailID { get; set; }
        public Nullable<long> CategoryAttributeID { get; set; }
        public string Value { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<bool> IsGlobal { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual CategoryAttributeMast CategoryAttributeMast { get; set; }
        public virtual CompanyMast CompanyMast { get; set; }
    }
}
