//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp.Core.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMarketEntities : DbContext
    {
        public EMarketEntities()
            : base("name=EMarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttributeMast> AttributeMasts { get; set; }
        public virtual DbSet<BrandMast> BrandMasts { get; set; }
        public virtual DbSet<CategoryAtrributeGroup> CategoryAtrributeGroups { get; set; }
        public virtual DbSet<CategoryAttributeDetail> CategoryAttributeDetails { get; set; }
        public virtual DbSet<CategoryAttributeMast> CategoryAttributeMasts { get; set; }
        public virtual DbSet<CategoryMast> CategoryMasts { get; set; }
        public virtual DbSet<CompanyEmployeeMast> CompanyEmployeeMasts { get; set; }
        public virtual DbSet<CompanyMast> CompanyMasts { get; set; }
        public virtual DbSet<EmployeeMaster> EmployeeMasters { get; set; }
        public virtual DbSet<ProdcutMast> ProdcutMasts { get; set; }
        public virtual DbSet<ProductDetail> ProductDetails { get; set; }
        public virtual DbSet<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual DbSet<PurchaseMast> PurchaseMasts { get; set; }
        public virtual DbSet<SaleDetail> SaleDetails { get; set; }
        public virtual DbSet<SaleMast> SaleMasts { get; set; }
    }
}
