//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseDetail()
        {
            this.SaleDetails = new HashSet<SaleDetail>();
        }
    
        public long PurchaseDetailID { get; set; }
        public Nullable<long> PurchaseID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> DiscountPer { get; set; }
        public Nullable<decimal> DiscountAmt { get; set; }
        public Nullable<decimal> NetTotal { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> AVat { get; set; }
        public Nullable<decimal> FinalTotal { get; set; }
    
        public virtual ProdcutMast ProdcutMast { get; set; }
        public virtual PurchaseMast PurchaseMast { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleDetail> SaleDetails { get; set; }
    }
}
