//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDetail
    {
        public long SaleDetailID { get; set; }
        public Nullable<long> SaleID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<long> PurchaseDetailID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> DiscountPer { get; set; }
        public Nullable<decimal> DiscountAmt { get; set; }
        public Nullable<decimal> NetTotal { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> AVat { get; set; }
        public Nullable<decimal> FinalTotal { get; set; }
    
        public virtual ProdcutMast ProdcutMast { get; set; }
        public virtual PurchaseDetail PurchaseDetail { get; set; }
        public virtual SaleMast SaleMast { get; set; }
    }
}
