//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryAtrributeGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryAtrributeGroup()
        {
            this.CategoryAttributeMasts = new HashSet<CategoryAttributeMast>();
        }
    
        public long CatAttGroupID { get; set; }
        public string CatAttGroupName { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<bool> IsGLobal { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual CategoryMast CategoryMast { get; set; }
        public virtual CompanyMast CompanyMast { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryAttributeMast> CategoryAttributeMasts { get; set; }
    }
}
