//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryAttributeMast
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryAttributeMast()
        {
            this.CategoryAttributeDetails = new HashSet<CategoryAttributeDetail>();
        }
    
        public long CategoryAttributeID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> AttributeID { get; set; }
        public Nullable<long> CatAttGroupID { get; set; }
        public string UnitName { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<bool> IsGlobal { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual AttributeMast AttributeMast { get; set; }
        public virtual CategoryAtrributeGroup CategoryAtrributeGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryAttributeDetail> CategoryAttributeDetails { get; set; }
        public virtual CategoryMast CategoryMast { get; set; }
        public virtual CompanyMast CompanyMast { get; set; }
    }
}
